package cn.yswu.mapper;

import cn.yswu.pojo.Film;
import java.util.List;

public interface FilmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    int insert(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    Film selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    List<Film> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    int updateByPrimaryKey(Film record);
}