package cn.yswu.pojo;

import java.util.Date;

public class Actor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.update_time
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.id
     *
     * @return the value of actor.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.id
     *
     * @param id the value for actor.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.name
     *
     * @return the value of actor.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.name
     *
     * @param name the value for actor.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.update_time
     *
     * @return the value of actor.update_time
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.update_time
     *
     * @param updateTime the value for actor.update_time
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}