package cn.yswu.pojo;

public class Film {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.id
     *
     * @return the value of film.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.id
     *
     * @param id the value for film.id
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.name
     *
     * @return the value of film.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.name
     *
     * @param name the value for film.name
     *
     * @mbg.generated Sat Jul 17 16:17:01 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}